<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class QuranSurahSeeder extends Seeder
{
    public function run(): void
    {
        $surahs = [
            ['id' => 1, 'name_ar' => 'الفاتحة', 'name_id' => 'Al-Fatihah', 'total_verses' => 7, 'type' => 'meccan'],
            ['id' => 2, 'name_ar' => 'البقرة', 'name_id' => 'Al-Baqarah', 'total_verses' => 286, 'type' => 'medinan'],
            ['id' => 3, 'name_ar' => 'آل عمران', 'name_id' => 'Ali Imran', 'total_verses' => 200, 'type' => 'medinan'],
            ['id' => 4, 'name_ar' => 'النساء', 'name_id' => 'An-Nisa\'', 'total_verses' => 176, 'type' => 'medinan'],
            ['id' => 5, 'name_ar' => 'المائدة', 'name_id' => 'Al-Ma\'idah', 'total_verses' => 120, 'type' => 'medinan'],
            ['id' => 6, 'name_ar' => 'الأنعام', 'name_id' => 'Al-An\'am', 'total_verses' => 165, 'type' => 'meccan'],
            ['id' => 7, 'name_ar' => 'الأعراف', 'name_id' => 'Al-A\'raf', 'total_verses' => 206, 'type' => 'meccan'],
            ['id' => 8, 'name_ar' => 'الأنفال', 'name_id' => 'Al-Anfal', 'total_verses' => 75, 'type' => 'medinan'],
            ['id' => 9, 'name_ar' => 'التوبة', 'name_id' => 'At-Taubah', 'total_verses' => 129, 'type' => 'medinan'],
            ['id' => 10, 'name_ar' => 'يونس', 'name_id' => 'Yunus', 'total_verses' => 109, 'type' => 'meccan'],
            ['id' => 11, 'name_ar' => 'هود', 'name_id' => 'Hud', 'total_verses' => 123, 'type' => 'meccan'],
            ['id' => 12, 'name_ar' => 'يوسف', 'name_id' => 'Yusuf', 'total_verses' => 111, 'type' => 'meccan'],
            ['id' => 13, 'name_ar' => 'الرعد', 'name_id' => 'Ar-Ra\'d', 'total_verses' => 43, 'type' => 'medinan'],
            ['id' => 14, 'name_ar' => 'إبراهيم', 'name_id' => 'Ibrahim', 'total_verses' => 52, 'type' => 'meccan'],
            ['id' => 15, 'name_ar' => 'الحجر', 'name_id' => 'Al-Hijr', 'total_verses' => 99, 'type' => 'meccan'],
            ['id' => 16, 'name_ar' => 'النحل', 'name_id' => 'An-Nahl', 'total_verses' => 128, 'type' => 'meccan'],
            ['id' => 17, 'name_ar' => 'الإسراء', 'name_id' => 'Al-Isra\'', 'total_verses' => 111, 'type' => 'meccan'],
            ['id' => 18, 'name_ar' => 'الكهف', 'name_id' => 'Al-Kahf', 'total_verses' => 110, 'type' => 'meccan'],
            ['id' => 19, 'name_ar' => 'مريم', 'name_id' => 'Maryam', 'total_verses' => 98, 'type' => 'meccan'],
            ['id' => 20, 'name_ar' => 'طه', 'name_id' => 'Taha', 'total_verses' => 135, 'type' => 'meccan'],
            ['id' => 21, 'name_ar' => 'الأنبياء', 'name_id' => 'Al-Anbiya\'', 'total_verses' => 112, 'type' => 'meccan'],
            ['id' => 22, 'name_ar' => 'الحج', 'name_id' => 'Al-Hajj', 'total_verses' => 78, 'type' => 'medinan'],
            ['id' => 23, 'name_ar' => 'المؤمنون', 'name_id' => 'Al-Mu\'minun', 'total_verses' => 118, 'type' => 'meccan'],
            ['id' => 24, 'name_ar' => 'النور', 'name_id' => 'An-Nur', 'total_verses' => 64, 'type' => 'medinan'],
            ['id' => 25, 'name_ar' => 'الفرقان', 'name_id' => 'Al-Furqan', 'total_verses' => 77, 'type' => 'meccan'],
            ['id' => 26, 'name_ar' => 'الشعراء', 'name_id' => 'Asy-Syu\'ara\'', 'total_verses' => 227, 'type' => 'meccan'],
            ['id' => 27, 'name_ar' => 'النمل', 'name_id' => 'An-Naml', 'total_verses' => 93, 'type' => 'meccan'],
            ['id' => 28, 'name_ar' => 'القصص', 'name_id' => 'Al-Qasas', 'total_verses' => 88, 'type' => 'meccan'],
            ['id' => 29, 'name_ar' => 'العنكبوت', 'name_id' => 'Al-\'Ankabut', 'total_verses' => 69, 'type' => 'meccan'],
            ['id' => 30, 'name_ar' => 'الروم', 'name_id' => 'Ar-Rum', 'total_verses' => 60, 'type' => 'meccan'],
            ['id' => 31, 'name_ar' => 'لقمان', 'name_id' => 'Luqman', 'total_verses' => 34, 'type' => 'meccan'],
            ['id' => 32, 'name_ar' => 'السجدة', 'name_id' => 'As-Sajdah', 'total_verses' => 30, 'type' => 'meccan'],
            ['id' => 33, 'name_ar' => 'الأحزاب', 'name_id' => 'Al-Ahzab', 'total_verses' => 73, 'type' => 'medinan'],
            ['id' => 34, 'name_ar' => 'سبإ', 'name_id' => 'Saba\'', 'total_verses' => 54, 'type' => 'meccan'],
            ['id' => 35, 'name_ar' => 'فاطر', 'name_id' => 'Fatir', 'total_verses' => 45, 'type' => 'meccan'],
            ['id' => 36, 'name_ar' => 'يس', 'name_id' => 'Ya-Sin', 'total_verses' => 83, 'type' => 'meccan'],
            ['id' => 37, 'name_ar' => 'الصافات', 'name_id' => 'As-Saffat', 'total_verses' => 182, 'type' => 'meccan'],
            ['id' => 38, 'name_ar' => 'ص', 'name_id' => 'Sad', 'total_verses' => 88, 'type' => 'meccan'],
            ['id' => 39, 'name_ar' => 'الزمر', 'name_id' => 'Az-Zumar', 'total_verses' => 75, 'type' => 'meccan'],
            ['id' => 40, 'name_ar' => 'غافر', 'name_id' => 'Ghafir', 'total_verses' => 85, 'type' => 'meccan'],
            ['id' => 41, 'name_ar' => 'فصلت', 'name_id' => 'Fussilat', 'total_verses' => 54, 'type' => 'meccan'],
            ['id' => 42, 'name_ar' => 'الشورى', 'name_id' => 'Asy-Syura', 'total_verses' => 53, 'type' => 'meccan'],
            ['id' => 43, 'name_ar' => 'الزخرف', 'name_id' => 'Az-Zukhruf', 'total_verses' => 89, 'type' => 'meccan'],
            ['id' => 44, 'name_ar' => 'الدخان', 'name_id' => 'Ad-Dukhan', 'total_verses' => 59, 'type' => 'meccan'],
            ['id' => 45, 'name_ar' => 'الجاثية', 'name_id' => 'Al-Jasiyah', 'total_verses' => 37, 'type' => 'meccan'],
            ['id' => 46, 'name_ar' => 'الأحقاف', 'name_id' => 'Al-Ahqaf', 'total_verses' => 35, 'type' => 'meccan'],
            ['id' => 47, 'name_ar' => 'محمد', 'name_id' => 'Muhammad', 'total_verses' => 38, 'type' => 'medinan'],
            ['id' => 48, 'name_ar' => 'الفتح', 'name_id' => 'Al-Fath', 'total_verses' => 29, 'type' => 'medinan'],
            ['id' => 49, 'name_ar' => 'الحجرات', 'name_id' => 'Al-Hujurat', 'total_verses' => 18, 'type' => 'medinan'],
            ['id' => 50, 'name_ar' => 'ق', 'name_id' => 'Qaf', 'total_verses' => 45, 'type' => 'meccan'],
            ['id' => 51, 'name_ar' => 'الذاريات', 'name_id' => 'Az-Zariyat', 'total_verses' => 60, 'type' => 'meccan'],
            ['id' => 52, 'name_ar' => 'الطور', 'name_id' => 'At-Tur', 'total_verses' => 49, 'type' => 'meccan'],
            ['id' => 53, 'name_ar' => 'النجم', 'name_id' => 'An-Najm', 'total_verses' => 62, 'type' => 'meccan'],
            ['id' => 54, 'name_ar' => 'القمر', 'name_id' => 'Al-Qamar', 'total_verses' => 55, 'type' => 'meccan'],
            ['id' => 55, 'name_ar' => 'الرحمن', 'name_id' => 'Ar-Rahman', 'total_verses' => 78, 'type' => 'medinan'],
            ['id' => 56, 'name_ar' => 'الواقعة', 'name_id' => 'Al-Waqi\'ah', 'total_verses' => 96, 'type' => 'meccan'],
            ['id' => 57, 'name_ar' => 'الحديد', 'name_id' => 'Al-Hadid', 'total_verses' => 29, 'type' => 'medinan'],
            ['id' => 58, 'name_ar' => 'المجادلة', 'name_id' => 'Al-Mujadilah', 'total_verses' => 22, 'type' => 'medinan'],
            ['id' => 59, 'name_ar' => 'الحشر', 'name_id' => 'Al-Hasyr', 'total_verses' => 24, 'type' => 'medinan'],
            ['id' => 60, 'name_ar' => 'الممتحنة', 'name_id' => 'Al-Mumtahanah', 'total_verses' => 13, 'type' => 'medinan'],
            ['id' => 61, 'name_ar' => 'الصف', 'name_id' => 'As-Saff', 'total_verses' => 14, 'type' => 'medinan'],
            ['id' => 62, 'name_ar' => 'الجمعة', 'name_id' => 'Al-Jumu\'ah', 'total_verses' => 11, 'type' => 'medinan'],
            ['id' => 63, 'name_ar' => 'المنافقون', 'name_id' => 'Al-Munafiqun', 'total_verses' => 11, 'type' => 'medinan'],
            ['id' => 64, 'name_ar' => 'التغابن', 'name_id' => 'At-Taghabun', 'total_verses' => 18, 'type' => 'medinan'],
            ['id' => 65, 'name_ar' => 'الطلاق', 'name_id' => 'At-Talaq', 'total_verses' => 12, 'type' => 'medinan'],
            ['id' => 66, 'name_ar' => 'التحريم', 'name_id' => 'At-Tahrim', 'total_verses' => 12, 'type' => 'medinan'],
            ['id' => 67, 'name_ar' => 'الملك', 'name_id' => 'Al-Mulk', 'total_verses' => 30, 'type' => 'meccan'],
            ['id' => 68, 'name_ar' => 'القلم', 'name_id' => 'Al-Qalam', 'total_verses' => 52, 'type' => 'meccan'],
            ['id' => 69, 'name_ar' => 'الحاقة', 'name_id' => 'Al-Haqqah', 'total_verses' => 52, 'type' => 'meccan'],
            ['id' => 70, 'name_ar' => 'المعارج', 'name_id' => 'Al-Ma\'arij', 'total_verses' => 44, 'type' => 'meccan'],
            ['id' => 71, 'name_ar' => 'نوح', 'name_id' => 'Nuh', 'total_verses' => 28, 'type' => 'meccan'],
            ['id' => 72, 'name_ar' => 'الجن', 'name_id' => 'Al-Jinn', 'total_verses' => 28, 'type' => 'meccan'],
            ['id' => 73, 'name_ar' => 'المزمل', 'name_id' => 'Al-Muzzammil', 'total_verses' => 20, 'type' => 'meccan'],
            ['id' => 74, 'name_ar' => 'المدثر', 'name_id' => 'Al-Muddassir', 'total_verses' => 56, 'type' => 'meccan'],
            ['id' => 75, 'name_ar' => 'القيامة', 'name_id' => 'Al-Qiyamah', 'total_verses' => 40, 'type' => 'meccan'],
            ['id' => 76, 'name_ar' => 'الانسان', 'name_id' => 'Al-Insan', 'total_verses' => 31, 'type' => 'medinan'],
            ['id' => 77, 'name_ar' => 'المرسلات', 'name_id' => 'Al-Mursalat', 'total_verses' => 50, 'type' => 'meccan'],
            ['id' => 78, 'name_ar' => 'النبإ', 'name_id' => 'An-Naba\'', 'total_verses' => 40, 'type' => 'meccan'],
            ['id' => 79, 'name_ar' => 'النازعات', 'name_id' => 'An-Nazi\'at', 'total_verses' => 46, 'type' => 'meccan'],
            ['id' => 80, 'name_ar' => 'عبس', 'name_id' => '\'Abasa', 'total_verses' => 42, 'type' => 'meccan'],
            ['id' => 81, 'name_ar' => 'التكوير', 'name_id' => 'At-Takwir', 'total_verses' => 29, 'type' => 'meccan'],
            ['id' => 82, 'name_ar' => 'الإنفطار', 'name_id' => 'Al-Infitar', 'total_verses' => 19, 'type' => 'meccan'],
            ['id' => 83, 'name_ar' => 'المطففين', 'name_id' => 'Al-Mutaffifin', 'total_verses' => 36, 'type' => 'meccan'],
            ['id' => 84, 'name_ar' => 'الإنشقاق', 'name_id' => 'Al-Insyiqaq', 'total_verses' => 25, 'type' => 'meccan'],
            ['id' => 85, 'name_ar' => 'البروج', 'name_id' => 'Al-Buruj', 'total_verses' => 22, 'type' => 'meccan'],
            ['id' => 86, 'name_ar' => 'الطارق', 'name_id' => 'At-Tariq', 'total_verses' => 17, 'type' => 'meccan'],
            ['id' => 87, 'name_ar' => 'الأعلى', 'name_id' => 'Al-A\'la', 'total_verses' => 19, 'type' => 'meccan'],
            ['id' => 88, 'name_ar' => 'الغاشية', 'name_id' => 'Al-Gasyiyah', 'total_verses' => 26, 'type' => 'meccan'],
            ['id' => 89, 'name_ar' => 'الفجر', 'name_id' => 'Al-Fajr', 'total_verses' => 30, 'type' => 'meccan'],
            ['id' => 90, 'name_ar' => 'البلد', 'name_id' => 'Al-Balad', 'total_verses' => 20, 'type' => 'meccan'],
            ['id' => 91, 'name_ar' => 'الشمس', 'name_id' => 'Asy-Syams', 'total_verses' => 15, 'type' => 'meccan'],
            ['id' => 92, 'name_ar' => 'الليل', 'name_id' => 'Al-Lail', 'total_verses' => 21, 'type' => 'meccan'],
            ['id' => 93, 'name_ar' => 'الضحى', 'name_id' => 'Ad-Duha', 'total_verses' => 11, 'type' => 'meccan'],
            ['id' => 94, 'name_ar' => 'الشرح', 'name_id' => 'Asy-Syarh', 'total_verses' => 8, 'type' => 'meccan'],
            ['id' => 95, 'name_ar' => 'التين', 'name_id' => 'At-Tin', 'total_verses' => 8, 'type' => 'meccan'],
            ['id' => 96, 'name_ar' => 'العلق', 'name_id' => 'Al-\'Alaq', 'total_verses' => 19, 'type' => 'meccan'],
            ['id' => 97, 'name_ar' => 'القدر', 'name_id' => 'Al-Qadr', 'total_verses' => 5, 'type' => 'meccan'],
            ['id' => 98, 'name_ar' => 'البينة', 'name_id' => 'Al-Bayyinah', 'total_verses' => 8, 'type' => 'medinan'],
            ['id' => 99, 'name_ar' => 'الزلزلة', 'name_id' => 'Az-Zalzalah', 'total_verses' => 8, 'type' => 'medinan'],
            ['id' => 100, 'name_ar' => 'العاديات', 'name_id' => 'Al-\'Adiyat', 'total_verses' => 11, 'type' => 'meccan'],
            ['id' => 101, 'name_ar' => 'القارعة', 'name_id' => 'Al-Qari\'ah', 'total_verses' => 11, 'type' => 'meccan'],
            ['id' => 102, 'name_ar' => 'التكاثر', 'name_id' => 'At-Takasur', 'total_verses' => 8, 'type' => 'meccan'],
            ['id' => 103, 'name_ar' => 'العصر', 'name_id' => 'Al-\'Asr', 'total_verses' => 3, 'type' => 'meccan'],
            ['id' => 104, 'name_ar' => 'الهمزة', 'name_id' => 'Al-Humazah', 'total_verses' => 9, 'type' => 'meccan'],
            ['id' => 105, 'name_ar' => 'الفيل', 'name_id' => 'Al-Fil', 'total_verses' => 5, 'type' => 'meccan'],
            ['id' => 106, 'name_ar' => 'قريش', 'name_id' => 'Quraisy', 'total_verses' => 4, 'type' => 'meccan'],
            ['id' => 107, 'name_ar' => 'الماعون', 'name_id' => 'Al-Ma\'un', 'total_verses' => 7, 'type' => 'meccan'],
            ['id' => 108, 'name_ar' => 'الكوثر', 'name_id' => 'Al-Kausar', 'total_verses' => 3, 'type' => 'meccan'],
            ['id' => 109, 'name_ar' => 'الكافرون', 'name_id' => 'Al-Kafirun', 'total_verses' => 6, 'type' => 'meccan'],
            ['id' => 110, 'name_ar' => 'النصر', 'name_id' => 'An-Nasr', 'total_verses' => 3, 'type' => 'medinan'],
            ['id' => 111, 'name_ar' => 'المسد', 'name_id' => 'Al-Lahab', 'total_verses' => 5, 'type' => 'meccan'],
            ['id' => 112, 'name_ar' => 'الإخلاص', 'name_id' => 'Al-Ikhlas', 'total_verses' => 4, 'type' => 'meccan'],
            ['id' => 113, 'name_ar' => 'الفلق', 'name_id' => 'Al-Falaq', 'total_verses' => 5, 'type' => 'meccan'],
            ['id' => 114, 'name_ar' => 'الناس', 'name_id' => 'An-Nas', 'total_verses' => 6, 'type' => 'meccan'],
        ];

        DB::table('quran_surahs')->insert($surahs);
    }
}
